### PR TITLE
Add GitHub workflow for cross-platform releases

### PR DESCRIPTION
**Pull request by Jarva**
This GitHub action will trigger automatically when creating a release and will create binaries for 5 common architectures and attach them to the aforementioned release.

Supported architectures (Windows, MacOS, Apple Silicon, Linux gnu/musl):
```
- { target: x86_64-apple-darwin         , os: macos-12,                                                  }
- { target: aarch64-apple-darwin        , os: macos-14,                                                  }
- { target: x86_64-pc-windows-msvc      , os: windows-2019,                                              }
- { target: x86_64-unknown-linux-gnu    , os: ubuntu-20.04, dpkg_arch: amd64,            use-cross: true }
- { target: x86_64-unknown-linux-musl   , os: ubuntu-20.04, dpkg_arch: musl-linux-amd64, use-cross: true }
```

Used https://github.com/sharkdp/bat/blob/master/.github/workflows/CICD.yml as reference, which is licensed under MIT

Additional steps may be to package the Mac binaries as a DMG and the Linux binaries as a flatpack.

### CODE REVIEW

**Comment by RealRTTV** [comment]
have you tested that it works yourself?

**Comment by RealRTTV** [comment]
or well... can you?

**Comment by Jarva** [comment]
I've tested the Linux and Apple Silicons builds and they run for me. The macOS build seems to have some scaling issues with high dpi displays but it's not a functionality issue. I'm unable to test the x86 MacOS or the Windows build myself.
Screenshot 2024-06-13 at 20 14 49

**Comment by Jarva** [comment]
The built artifacts are available on a release on my fork: https://github.com/Jarva/nbtworkbench/releases/tag/1.3.1

**Comment by Jarva** [comment]
I had someone on Discord test the Windows build, and they reported back all good

**Comment by RealRTTV** [comment]
lgtm, tysm <3

**Pull request merged**
